DATABASE_CONNECTION_STRING = "postgres://user-easydev-api:Fr8h8EDi5FpfztnGMTetyO6PJXjpBB3z@db.shuttle.rs:5432/db-easydev-api"
JWT_SECRET = "djkfekls389w7usijdknpw9847reushljkndfoiask47e8wzusis3rew3sex34y78ewzsuhj3e"
JWT_SUBJECT = "https://github.com/basillica"
JWT_AUDIENCE = "basillica"
JWT_ISSUER = "https://github.com/basillica"